services:
  ngspice-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6543:5000"
    volumes:
      - type: bind
        source: ./simulations
        target: /app/simulations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s